import './InfoPage.css';

const featureList = [
  { icon: '🎤', title: 'AI Mock Interviews', desc: 'Practice with realistic, role-specific interview questions generated by AI.' },
  { icon: '🎥', title: 'Live Video Simulation', desc: 'Simulate a real interview setting with webcam-based practice sessions.' },
  { icon: '👁️', title: 'Emotion & Eye Tracking', desc: 'Get feedback on confidence, eye contact, and body language.' },
  { icon: '📄', title: 'Resume Analyzer', desc: 'AI reviews your resume and suggests improvements tailored to your target role.' },
  { icon: '🤝', title: 'Recruiter Connect', desc: 'Get discovered by recruiters based on your interview performance.' },
  { icon: '📱', title: 'Mobile App', desc: 'Practice on the go with our companion mobile app.' },
];

const Features = () => (
  <div className="info-page">
    <h1>Features</h1>
    <p className="subtitle">Everything you need to prepare for your next technical interview.</p>
    <div className="info-grid">
      {featureList.map((f) => (
        <div key={f.title} className="info-card">
          <div className="info-icon">{f.icon}</div>
          <h3>{f.title}</h3>
          <p>{f.desc}</p>
        </div>
      ))}
    </div>
  </div>
);

export default Features;